package main

type GameBody struct {
	AppID                      string
	Name                       string
	Release_date               string
	Estimated_owners           string
	Peak_CCU                   string
	Required_age               string
	Price                      string
	DLC_count                  string
	About_the_game             string
	Supported_languages        string
	Full_audio_languages       string
	Reviews                    string
	Header_image               string
	Website                    string
	Support_url                string
	Support_email              string
	Windows                    string
	Mac                        string
	Linux                      string
	Metacritic_score           string
	Metacritic_url             string
	User_score                 string
	Positive                   string
	Negative                   string
	Score_rank                 string
	Achievements               string
	Recommendations            string
	Notes                      string
	Average_playtime_forever   string
	Average_playtime_two_weeks string
	Median_playtime_forever    string
	Median_playtime_two_weeks  string
	Developers                 string
	Publishers                 string
	Categories                 string
	Genres                     string
	Tags                       string
	Screenshots                string
	Movies                     string
}
