// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/delete-game": {
            "delete": {
                "description": "Deletes a game",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/delete-game-concept": {
            "delete": {
                "description": "Deletes a game concept",
                "produces": [
                    "application/json"
                ],
                "summary": "Delete game concept",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/favorite-game": {
            "post": {
                "description": "Favorite a game",
                "produces": [
                    "application/json"
                ],
                "summary": "Favorite a game",
                "parameters": [
                    {
                        "description": "AppID",
                        "name": "AppID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "UserID",
                        "name": "UserID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/filter-game": {
            "get": {
                "description": "Filters games (currently by Genre, Tags, and Title)",
                "produces": [
                    "application/json"
                ],
                "summary": "Filter games",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Genre",
                        "name": "Genre",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "tags",
                        "name": "tags",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "title",
                        "name": "title",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get-all-game-concepts": {
            "get": {
                "description": "Get all game concepts",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all game concepts",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get-all-games": {
            "get": {
                "description": "Get all games",
                "produces": [
                    "application/json"
                ],
                "summary": "Get all games",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/get-favorite-games": {
            "get": {
                "description": "Get favorite games by UserID",
                "produces": [
                    "application/json"
                ],
                "summary": "Get favorite games",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UserID",
                        "name": "UserID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Check if the server is up and running",
                "produces": [
                    "application/json"
                ],
                "summary": "Ping the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/request": {
            "get": {
                "description": "select all of one value that matches a column",
                "produces": [
                    "application/json"
                ],
                "summary": "request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "sele",
                        "name": "sele",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collum",
                        "name": "collum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "equal",
                        "name": "equal",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/request-game": {
            "get": {
                "description": "request a game by AppID",
                "produces": [
                    "application/json"
                ],
                "summary": "request a game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppID",
                        "name": "AppID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/send-game": {
            "post": {
                "description": "Sends a game to the database",
                "produces": [
                    "application/json"
                ],
                "summary": "Send game",
                "parameters": [
                    {
                        "description": "AppID",
                        "name": "AppID",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Name",
                        "name": "Name",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Release_date",
                        "name": "Release_date",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Estimated_owners",
                        "name": "Estimated_owners",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Peak_CCU",
                        "name": "Peak_CCU",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Required_age",
                        "name": "Required_age",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Price",
                        "name": "Price",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "number"
                        }
                    },
                    {
                        "description": "DLC_count",
                        "name": "DLC_count",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "About_the_game",
                        "name": "About_the_game",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Supported_languages",
                        "name": "Supported_languages",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Full_audio_languages",
                        "name": "Full_audio_languages",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Reviews",
                        "name": "Reviews",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Header_image",
                        "name": "Header_image",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Website",
                        "name": "Website",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Support_url",
                        "name": "Support_url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Support_email",
                        "name": "Support_email",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Windows",
                        "name": "Windows",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "description": "Mac",
                        "name": "Mac",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "description": "Linux",
                        "name": "Linux",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "boolean"
                        }
                    },
                    {
                        "description": "Metacritic_score",
                        "name": "Metacritic_score",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Metacritic_url",
                        "name": "Metacritic_url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "User_score",
                        "name": "User_score",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Positive",
                        "name": "Positive",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Negative",
                        "name": "Negative",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Score_rank",
                        "name": "Score_rank",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Achievements",
                        "name": "Achievements",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Recommendations",
                        "name": "Recommendations",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Notes",
                        "name": "Notes",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Average_playtime_forever",
                        "name": "Average_playtime_forever",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Average_playtime_two_weeks",
                        "name": "Average_playtime_two_weeks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Median_playtime_forever",
                        "name": "Median_playtime_forever",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Median_playtime_two_weeks",
                        "name": "Median_playtime_two_weeks",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    },
                    {
                        "description": "Developers",
                        "name": "Developers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Publishers",
                        "name": "Publishers",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Categories",
                        "name": "Categories",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Genres",
                        "name": "Genres",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Tags",
                        "name": "Tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Screenshots",
                        "name": "Screenshots",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "Movies",
                        "name": "Movies",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/send-game-concept": {
            "post": {
                "description": "Sends a game concept to the database",
                "produces": [
                    "application/json"
                ],
                "summary": "Send game concept",
                "parameters": [
                    {
                        "description": "title",
                        "name": "title",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "developer_id",
                        "name": "developer_id",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "description",
                        "name": "description",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "genre",
                        "name": "genre",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    },
                    {
                        "description": "tags",
                        "name": "tags",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/shutdown": {
            "get": {
                "description": "Shutdown the server",
                "produces": [
                    "application/json"
                ],
                "summary": "Shutdown the server",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update-game": {
            "put": {
                "description": "Updates a game after creation",
                "produces": [
                    "application/json"
                ],
                "summary": "Update game",
                "parameters": [
                    {
                        "type": "string",
                        "description": "AppID",
                        "name": "AppID",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collum",
                        "name": "collum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "value",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/update-game-concept": {
            "put": {
                "description": "Updates a game concept after creation",
                "produces": [
                    "application/json"
                ],
                "summary": "Update game concept",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id",
                        "name": "id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "collum",
                        "name": "collum",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "value",
                        "name": "value",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
