info:
  contact: {}
paths:
  /ping:
    get:
      description: Check if the server is up and running
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Ping the server
swagger: "2.0"
