name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Gin Server, Pull Changes, and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            # Stop the server if it's running
            curl -X GET https://localhost:8080/shutdown || true

            # Navigate to the project directory, pull latest changes
            cd coms-senior-design/backend
            git pull

            # Start the server
            sudo nohup go run main.go
