name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go environment
        uses: actions/setup-go@v2
        with:
          go-version: 1.20

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Go application
        run: go build -o main ./backend

      - name: Copy binary to server and restart service
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          source: "./main"
          target: "/home/ec2-user/coms-senior-design/backend"

      - name: Restart Gin Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            sudo systemctl restart gin-server.service
