name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Gin Server, Pull Changes, and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            sudo pkill -f "main.go" || true  # Stops the Gin server, doesn't error if no process is found
            cd /coms-senior-design/backend
            git pull
            sudo go run main.go &  # Starts the Gin server in the background

            exit 0 # Prevents the action from failing if the server is already stopped