name: Deploy Backend to EC2

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop Gin Server, Pull Changes, and Restart
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.BACKEND_USERNAME }}
          key: ${{ secrets.BACKEND_SSH_KEY }}
          script: |
            # Stop the server if it's running
            if [ -f /coms-senior-design/backend/server.pid ]; then
              sudo kill $(cat /coms-senior-design/backend/server.pid) || true
              sudo rm /coms-senior-design/backend/server.pid
            fi

            # Navigate to the project directory, pull latest changes
            cd coms-senior-design/backend
            git pull

            # Start the server and save its PID (for use in next Action run)
            sudo nohup go run main.go > server.log 2>&1 & echo $! > server.pid
